name: Java CI with Maven

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Navigate to the specific module containing your Spring Boot application
    - name: Change Directory to SpringBoot-ApacheKafka-Project
      run: cd disturbance-report/workflow/SpringBoot-ApacheKafka-Project

    # Build and test the Spring Boot application within the module
    - name: Build with Maven
      run: mvn -B test package --file pom.xml
